name: Trello Branch Check

on:
  pull_request:

jobs:
  trello-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set secrets as env
        run: |
          echo "TRELLO_KEY=${{ secrets.TRELLO_KEY }}" >> $GITHUB_ENV
          echo "TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}" >> $GITHUB_ENV
          echo "TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }}" >> $GITHUB_ENV

      - name: Check Trello card exists
        if: ${{ github.head_ref != github.base_ref }}
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          BRANCH_CARD_ID=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+$')

          echo "Debug: Branch Name = $BRANCH_NAME"
          echo "Debug: Branch Card ID = $BRANCH_CARD_ID"

          # Tek kart sorgula
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://api.trello.com/1/boards/$TRELLO_BOARD_ID/cards/$BRANCH_CARD_ID?key=$TRELLO_KEY&token=$TRELLO_TOKEN")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Hata: Branch ile eşleşen Trello kartı bulunamadı (HTTP $RESPONSE)."
            exit 1
          fi

          echo "Başarılı: Trello kartı bulundu ✅"
