name: Trello Branch Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  trello-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set secrets as env
        run: |
          echo "TRELLO_KEY=${{ secrets.TRELLO_KEY }}" >> $GITHUB_ENV
          echo "TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}" >> $GITHUB_ENV
          echo "TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }}" >> $GITHUB_ENV

      - name: Check Trello card exists
        if: github.ref_name != 'main'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_CARD_ID=$(echo "$BRANCH_NAME" | grep -oP '\d+$')

          echo "Debug: Branch Name = $BRANCH_NAME"
          echo "Debug: Branch Card ID = $BRANCH_CARD_ID"

          # Trello kart ID’lerini al
          CARDS=$(curl -s "https://api.trello.com/1/boards/$TRELLO_BOARD_ID/cards?key=$TRELLO_KEY&token=$TRELLO_TOKEN" | jq -r '.[].idShort')

          echo "Debug: Trello Cards:"
          echo "$CARDS"

          # Branch ID Trello kartlarında var mı kontrol et
          if ! echo "$CARDS" | grep -Fxq "$BRANCH_CARD_ID"; then
            echo "Hata: Branch ile eşleşen Trello kartı bulunamadı."
            exit 1
          fi
